using API.Interfaces;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using API.Entities;
using Microsoft.AspNetCore.Identity;
using System.Security.Cryptography;

namespace API.Services;

public class TokenService(IConfiguration config, UserManager<AppUser> userManager) : ITokenService //IConfiguration is used to access the configuration settings in the appsettings.json file, specifically to retrieve the TokenKey value that is used to sign the JWT tokens. By injecting IConfiguration into the TokenService constructor, we can easily access the configuration settings and use them to generate secure tokens for user authentication.
{
    public async Task<string> CreateToken(AppUser user)
    {
        var tokenKey = config["TokenKey"] ?? throw new Exception("TokenKey not found in configuration");
        if (tokenKey.Length < 64)
        {
            throw new Exception("TokenKey must be at least 64 characters long");
        }

        var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(tokenKey)); //SymmetricSecurityKey is used to create a security key for signing the JWT tokens. It takes a byte array as input, which is generated by encoding the TokenKey string from the configuration using UTF-8 encoding. This key is then used in the signing credentials to ensure that the tokens are securely signed and can be validated by the server when they are received in subsequent requests.

        var claims = new List<Claim> //Claims are used to store information about the user that is included in the JWT token. In this case, we are adding claims for the user's email, unique identifier (Id), and username. These claims can be accessed by the server when the token is received in subsequent requests, allowing us to identify the user and perform authorization checks based on their identity and roles. By including these claims in the token, we can ensure that the necessary information about the user is available for authentication and authorization purposes throughout the application.
        {
            new(ClaimTypes.Email, user.Email!),
            new(ClaimTypes.NameIdentifier, user.Id.ToString()),
            new(ClaimTypes.Name, user.UserName!)
        };

        var roles = await userManager.GetRolesAsync(user); //GetRolesAsync is a method of the UserManager class that retrieves the roles associated with the specified user. In this case, we are calling this method to get the roles for the user and then adding them as claims to the JWT token. By including the user's roles in the token, we can perform role-based authorization checks in subsequent requests, allowing us to control access to certain resources or actions based on the user's assigned roles.
        claims.AddRange(roles.Select(role => new Claim(ClaimTypes.Role, role)));

        var creds = new SigningCredentials(key, SecurityAlgorithms.HmacSha512Signature); //SigningCredentials are used to specify the security key and algorithm that will be used to sign the JWT token. In this case, we are using the symmetric security key that we created earlier and the HMAC SHA-512 algorithm for signing. This ensures that the token is securely signed and can be validated by the server when it is received in subsequent requests. By using strong signing credentials, we can help protect against tampering and ensure the integrity of the tokens used for user authentication.

        var tokenDescriptor = new SecurityTokenDescriptor //SecurityTokenDescriptor is used to define the properties of the JWT token that we want to create. It includes the claims that we want to include in the token, the expiration time for the token (in this case, 7 days), and the signing credentials that we defined earlier. By setting these properties in the token descriptor, we can ensure that the generated token contains the necessary information about the user and is securely signed for authentication purposes.
        {
            Subject = new ClaimsIdentity(claims),
            Expires = DateTime.Now.AddMinutes(10),
            SigningCredentials = creds
        };

        var tokenHandler = new JwtSecurityTokenHandler(); //JwtSecurityTokenHandler is used to create and write the JWT token based on the token descriptor that we defined. It provides methods for creating the token and converting it to a string format that can be returned to the client. By using the JwtSecurityTokenHandler, we can easily generate secure tokens for user authentication and ensure that they are properly formatted for use in subsequent requests.

        var token = tokenHandler.CreateToken(tokenDescriptor); //CreateToken is a method of the JwtSecurityTokenHandler that takes the token descriptor as input and generates a JWT token based on the properties defined in the descriptor. This method creates a token that includes the specified claims, expiration time, and signing credentials, allowing us to generate secure tokens for user authentication.

        return tokenHandler.WriteToken(token); //WriteToken is a method of the JwtSecurityTokenHandler that takes the generated token as input and converts it to a string format that can be returned to the client. This method serializes the token into a compact, URL-safe string representation that can be easily transmitted in HTTP headers or other communication channels. By using WriteToken, we can ensure that the generated JWT token is properly formatted for use in subsequent requests and can be easily consumed by the client for authentication purposes.
    }

    public string GenerateRefreshToken()
    {
       var randomBytes = RandomNumberGenerator.GetBytes(64);
       return Convert.ToBase64String(randomBytes); 
    }
}