using API.Data;
using API.Interfaces;
using API.Services;
using API.Middlewares;
using API.Entities;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Text;
using API.Helpers;
using Microsoft.OpenApi.Models;

var builder = WebApplication.CreateBuilder(args);

/* =======================
   Database
   ======================= */
   //This options are passed to the base DbContext constructor in AppDBContext, which is required for EF Core to function properly.
   //Because AppDBContext needs to know how to conect to the dabatase. 
builder.Services.AddDbContext<AppDBContext>(options =>
{
    options.UseSqlite(
        builder.Configuration.GetConnectionString("DefaultConnection")
    );
});

/* =======================
   Controllers
   ======================= */
//Formatting all time to proper utc date time in apis
builder.Services.AddControllers()
    .AddJsonOptions(options =>
    {
        options.JsonSerializerOptions.Converters.Add(new UtcDateTimeConverter());
    });

/* =======================
   CORS
   ======================= */
builder.Services.AddCors(options =>
{
    options.AddPolicy("CorsPolicy", policy =>
    {
        policy
            .AllowAnyHeader()
            .AllowAnyMethod()
            .AllowCredentials()
            .WithOrigins("http://localhost:4200", "https://localhost:4200");
    });
});

/* =======================
   Routing
   ======================= */
builder.Services.AddRouting(options =>
{
    options.LowercaseUrls = true;
});

//ASP.NET Core Identity configuration
builder.Services.AddIdentityCore<AppUser>(opt=> {
    opt.Password.RequireNonAlphanumeric = false;
    opt.User.RequireUniqueEmail = true;
}) 
.AddRoles<IdentityRole>()
.AddEntityFrameworkStores<AppDBContext>();

/* =======================
   Authentication (JWT)
   ======================= */
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme) //This line sets the default authentication scheme to JWT Bearer, which means that the application will expect incoming requests to include a JWT token in the Authorization header for authentication. By specifying this scheme, we can easily configure the application to use JWT tokens for securing our APIs and handling user authentication.
    .AddJwtBearer(options => //This method is used to configure the JWT Bearer authentication handler, which is responsible for validating incoming JWT tokens and authenticating users based on those tokens. By calling this method, we can specify various options for how the JWT tokens should be validated, such as the signing key, issuer, audience, and other parameters that are necessary for ensuring the security and integrity of our authentication process.
    {
        var tokenKey = builder.Configuration["TokenKey"]
            ?? throw new Exception("TokenKey not found in configuration");

        options.TokenValidationParameters = new TokenValidationParameters //This property is used to specify the parameters that will be used to validate incoming JWT tokens. By setting this property, we can define the rules and requirements for how the tokens should be validated, such as checking the signing key, issuer, audience, and other aspects of the token's structure and content. This is an essential part of the authentication process, as it ensures that only valid and properly signed tokens are accepted by the application, thereby enhancing security and preventing unauthorized access.
        {
            ValidateIssuerSigningKey = true, // This property is used to specify whether the signing key of the JWT token should be validated during the token validation process. By setting this property to true, we are indicating that the application should check if the token's signature is valid and matches the expected signing key. This is an important security measure, as it helps ensure that the token has not been tampered with and that it was indeed issued by a trusted authority. If the signing key validation fails, the token will be rejected and the authentication process will not succeed.
            IssuerSigningKey = new SymmetricSecurityKey( // This property is used to specify the signing key that will be used to validate the signature of incoming JWT tokens. In this case, we are creating a new instance of SymmetricSecurityKey, which is a type of security key that uses a symmetric algorithm for signing and validating tokens. The key is generated by encoding the tokenKey string from the configuration using UTF-8 encoding. This signing key will be used to verify the authenticity of the JWT tokens and ensure that they have not been tampered with during transmission.
                Encoding.UTF8.GetBytes(tokenKey)
            ),
            ValidateIssuer = false, // In this case, we are not validating the issuer of the token, which means that we are not checking if the token was issued by a specific authority. This can be useful in scenarios where we want to allow tokens from multiple issuers or when we don't have a specific issuer to validate against. However, it's important to note that disabling issuer validation can potentially reduce the security of the authentication process, so it should be done with caution and only when necessary.
            ValidateAudience = false, // Similar to issuer validation, we are also not validating the audience of the token. This means that we are not checking if the token is intended for a specific audience or application. Disabling audience validation can be useful in scenarios where we want to allow tokens that are meant for multiple audiences or when we don't have a specific audience to validate against. However, like with issuer validation, it's important to consider the security implications of disabling audience validation and ensure that it aligns with the overall security requirements of the application.
            ClockSkew = TimeSpan.Zero //This property is used to specify the amount of time that the token validation process should allow for clock skew when validating the expiration time of a JWT token. By setting this property to TimeSpan.Zero, we are effectively disabling any allowance for clock skew, which means that the token will be considered expired immediately after its expiration time has passed. This can enhance security by ensuring that expired tokens are not accepted, but it also means that there is no grace period for potential discrepancies in system clocks between the token issuer and the token validator.
        };
    });

/* =======================
   Authorization
   ======================= */
builder.Services.AddAuthorizationBuilder()
    .AddPolicy("RequireAdminRole", policy => policy.RequireRole("Admin"))
    .AddPolicy("ModeratePhotoRole", policy => policy.RequireRole("Admin", "Moderator"));

// 

/* =======================
   Application Services
   ======================= */
   //This service is needed to generate JWT tokens for user authentication. By registering it in the dependency injection container, we can easily inject it into our controllers and other services where we need to create tokens for authenticated users. This allows us to centralize our token generation logic and makes it easier to maintain and update in the future if needed.
builder.Services.AddScoped<ITokenService, TokenService>(); //Scoped means a new instance of the service will be created for each HTTP request, and that same instance will be used throughout the entire request. This is useful for services that need to maintain state or perform operations that are specific to a single request, such as database contexts or services that handle user authentication. By using scoped services, we can ensure that each request gets its own instance of the service, which can help prevent issues with shared state and improve the overall performance and reliability of the application.

builder.Services.AddScoped<LogUserActivity>();

builder.Services.AddScoped<IPhotoService, PhotoService>();

builder.Services.AddScoped<IMemberRepository, MemberRepository>();

builder.Services.AddScoped<ILikesRepository,LikesReporitory>();

builder.Services.AddScoped<IMessageRepository, MessageRepository>();

builder.Services.Configure<CloudinarySettings>(builder.Configuration.GetSection("CloudinarySettings")); //Key should be same as app settings

// Swagger/OpenAPI (only enabled in Development)
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new OpenApiInfo { Title = "API", Version = "v1" });

    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Description = "JWT Authorization header using the Bearer scheme. Enter 'Bearer {token}'",
        Name = "Authorization",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",
        BearerFormat = "JWT"
    });

    options.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" }
            },
            Array.Empty<string>()
        }
    });
});

var app = builder.Build();

/* =======================
   Middleware Pipeline
   ======================= */

app.UseMiddleware<ExceptionMiddleware>();

// Enable Swagger only in Development environment
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection(); //Not required if we enforce https in angular dev server, but good to have in production environment

app.UseRouting();

app.UseCors("CorsPolicy");

app.UseAuthentication(); // Who are you
app.UseAuthorization();  // What are you allowed to do

app.MapControllers();

//Creating scope outside http request pipeline to do migrations
using var scope = app.Services.CreateScope();
var services = scope.ServiceProvider;
try
{
    var context = services.GetRequiredService<AppDBContext>();
    var userManager = services.GetRequiredService<UserManager<AppUser>>();
    var roleManager = services.GetRequiredService<RoleManager<IdentityRole>>();
    await context.Database.MigrateAsync(); //Asynchronously applies pending migrations and creates the database if it does not already exist. This is a convenient way to ensure that the database schema is up to date with the latest migrations when the application starts. By calling this method, we can automatically apply any new migrations that have been added since the last time the application was run, which helps to keep the database schema in sync with the application's data model and ensures that any changes to the data model are properly reflected in the database.
    await Seed.SeedUsers(context, userManager, roleManager);
}
catch (Exception ex)
{
    var logger = services.GetRequiredService<ILogger<Program>>();
    logger.LogError(ex, "An error occured during migration");
}

app.Run();
